{% set name = "aiosqlite" %}
{% set version = "0.17.0" %}
{% set sha256 = "f0e6acc24bc4864149267ac82fb46dfb3be4455f99fe21df82609cc6e6baee51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit-core >=2,<4
    - typing-extensions >=3.7.2
  run:
    - python >=3.6
    - typing-extensions >=3.7.2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - aiosqlite

about:
  home: https://github.com/omnilib/aiosqlite
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: asyncio bridge to the standard sqlite3 module
  dev_url: https://github.com/omnilib/aiosqlite
